service: anon-group-bot

provider:
  name: aws
  runtime: python3.6
  profile:
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, '1362043851:AAFL26fjgBBYjyBK8bEEeFQ9r6QG01SGSto'}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

plugins:
  - serverless-python-requirements
